# Generated by Django 2.1.3 on 2018-11-11 22:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20181111_2109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostTexts',
            new_name='PostText',
        ),
    ]
