version: '3.6'

services:
  db:
    image: postgres:10.1-alpine
    container_name: djangodocker_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5434:5432
    networks:
      - main_network

  web:
    build: .
    container_name: djangodocker_web
    stdin_open: true
    tty: true
    command: tail -f /dev/null # Keep the container alive
    volumes:
      - .:/djangodocker
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=changemeinprod
    depends_on:
      - db
    networks:
      - main_network

volumes:
  postgres_data:

networks:
  main_network:
    driver: bridge
